version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: coyukdae-dev
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: coyukdae
      TZ: Asia/Seoul
    volumes:
      - ./data/mysql/:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

